### ISSUE TITLE
Unable to Run AirCast

### ISSUE THREAD

**Issue by mynameisdaniel32** [ains/aircast#8]
I can't work out where I've gone wrong, I've set things up on a Debian box (not using Vagrance as I couldn't get that to run in my environment). I more-or-less followed the steps [here](https://github.com/ains/aircast/issues/1#issuecomment-270019487). Whenever I try to run supervisor it fails. Checking the error file, I have the following showing repeatedly.

```
Traceback (most recent call last):
    File "/home/daniel/aircast/src/main.py", line 21 in <module>
        start_aircast(get_ip_address(args.iface), args.port)
    File "/home/daniel/aircast/src/util.py", line 11, in get_ip_address
  struct.pack('256s', ifname[:15]))[20:24])
IOERror: [Errno 19] No such device
```

Any help would be hugely appreciated as I'm completely stuck.

**Comment by axlroden** [comment]
Well he is not error handling if the interface doesn't exist.

It's trying to get an IP from the argument passed to it what interface did you feed it?

```
--iface
default eth0
Interface on which the AirCast web server will be exposed
```
